version: '2.0'
services:
  jenkins:
    image: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    links:
      - sonar
  sonar:
    image: sonarqube
    ports:
      - 9000:9000
      - 9092:9092